### PR TITLE
Fix wapm list for empty lockfiles

### LINKED ISSUE #96: wapm list after wapm uninstall shows empty tables
Installing then uninstalling a package breaks `wapm list`

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
resolves #96

### CODE REVIEW

File: src/commands/list.rs [hunk 1]
```diff
@@ -91,6 +112,14 @@ pub fn list(options: ListOpt) -> Result<(), failure::Error> {
         }
     }
 
+    if handle.len() == 0 {
```
Comment (xmclark) [inline src/commands/list.rs]: ⛳️ https://doc.rust-lang.org/std/string/struct.String.html#method.is_empty
