### PR TITLE
Shell out to the OS instead of invoking yarn/npm/pip directly

### LINKED ISSUE #291: The "wapm install --npm package/name" command doesn't work on Windows
### Describe the bug

When you use NVM to manage your NodeJS versions on Windows, the `npm` and `yarn` commands are actually scripts (`npm.cmd` and `yarn.ps1`) and not executables. 

That means running `wapm install --npm dynamite-bud/tutorial-01` will fail with a *"the npm command isn't installed"* error.

This happens on the latest version of the `wapm` CLI ([5484ea7](https://github.com/wasmerio/wapm-cli/commit/5484ea71be5a485252782b1b64e1f51645344f35)).

### Expected behavior

One way to deal with this is by using the OS's shell instead of invoking `yarn` or `npm` directly. That way, the shell will run scripts for you.

We should also allow people to override the path to their package manager (e.g. by setting a `$NPM_PATH` environment variable).

### Actual behavior

Currently, we are constructing the command blindly using hard-coded strings.

https://github.com/wasmerio/wapm-cli/blob/5484ea71be5a485252782b1b64e1f51645344f35/src/commands/install.rs#L308-L332

### PR DESCRIPTION
**Pull request by Michael-F-Bryan**
Fixes #291.

### CODE REVIEW

File: src/commands/install.rs [hunk 1]
```diff
@@ -296,30 +296,34 @@ impl Target {
...
     fn command(&self, url: &str, dev: bool) -> Command {
-        match self {
+        let shell_command = match self {
             Target::Npm => {
-                let mut cmd = Command::new("npm");
-                cmd.arg("install");
+                let mut cmd = format!("npm install {url}");
                 if dev {
-                    cmd.arg("--save-dev");
+                    cmd.push_str(" --dev");
```
Comment (fschutt) [inline src/commands/install.rs:303]: This will format it as `npm install https://blah.io--dev` with a lacking space

File: src/commands/install.rs [hunk 2]
```diff
@@ -296,30 +296,34 @@ impl Target {
...
-                cmd.arg(url);
                 cmd
             }
             Target::Yarn => {
-                let mut cmd = Command::new("yarn");
-                cmd.arg("add");
+                let mut cmd = format!("yarn add {url}");
                 if dev {
-                    cmd.arg("--dev");
+                    cmd.push_str(" --dev");
```
Comment (fschutt) [inline src/commands/install.rs:310]: same thing here

File: src/commands/install.rs [hunk 3]
```diff
@@ -296,30 +296,34 @@ impl Target {
...
-                let mut cmd = Command::new("pip");
-                cmd.arg("install").arg(url);
-                cmd
+                format!("pip install {url}")
             }
+        };
+
+        if cfg!(target_os = "windows") {
+            let mut cmd = Command::new("cmd");
+            cmd.arg("/C").arg(shell_command);
```
Comment (fschutt) [inline src/commands/install.rs:321]: I would actually leave it as is and just do `.arg(format!("{cmd:?}"))` instead of handling strings myself

File: src/commands/install.rs (hunk 1 above)
Comment (Michael-F-Bryan) [reply src/commands/install.rs:303]: There's a space in front of the `--dev`, so I think this should format correctly.

File: src/commands/install.rs (hunk 3 above)
Comment (Michael-F-Bryan) [reply src/commands/install.rs:321]: Can you show me a snippet of what you mean?

Comment (fschutt) [reply src/commands/install.rs:321]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=96ac77719eab17c711ced1d62298137b

Comment (Michael-F-Bryan) [reply src/commands/install.rs:314]: I think I see what you meant now. 

Are you suggesting passing the `cmd` variable that was originally constructed in our `match` to something like `Command::new("cmd.exe").arg("/C").arg(format!("{cmd:?}"))`? That way we reuse `Command`'s shell quoting logic.

So something like this:

```rust
let original_cmd = match self {
    Target::Npm => {
        let mut cmd = Command::new("npm");
        cmd.arg("install");
        if dev {
            cmd.arg("--save-dev");
        }
        cmd.arg(url);
        cmd
    }
    ...
};

if cfg!(target_os = "windows") {
    let mut cmd = Command::new("cmd");
    cmd.arg("/C").arg(format!("{original_cmd:?}"));
    cmd
} else {
    ...
}
```

Comment (fschutt) [reply src/commands/install.rs:314]: Yes that's what I meant, it also makes this PR shorter
